# Data Wrangling with pandas

This notebook demonstrates foundational data-wrangling techniques using a small veterinary-visit dataset. It covers DataFrame creation, inspection, filtering, missing-value handling, sorting, aggregation, grouping, and pivot tables.

## Skills demonstrated

- Creating a pandas DataFrame
- Selecting rows and columns with `loc` and `iloc`
- Filtering with Boolean conditions
- Handling missing values
- Updating, adding, and deleting rows
- Aggregating and grouping data
- Sorting values
- Creating pivot tables

## 1. Setup

In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)

## 2. Create the sample dataset

In [2]:
data = {
    "animal": ["cat", "cat", "snake", "dog", "dog", "cat", "snake", "cat", "dog", "dog"],
    "age": [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    "visits": [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    "priority": ["yes", "yes", "no", "yes", "no", "no", "no", "yes", "no", "no"],
}

labels = list("abcdefghij")

df = pd.DataFrame(data, index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

## 3. Inspect the DataFrame

### Basic structure and data types

In [3]:
df.info()

<class 'pandas.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     str
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 400.0+ bytes

### First three rows

In [4]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

## 4. Select rows and columns

### Select the `animal` and `age` columns

In [5]:
df[["animal", "age"]]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### Select rows at positions 3, 4, and 8 and display `animal` and `age`

In [6]:
df.iloc[[3, 4, 8]][["animal", "age"]]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

## 5. Filter records

### Records with more than three visits

In [7]:
df.loc[df["visits"] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

> The result is empty because no record in this sample has more than three visits.

### Records with missing ages

In [8]:
df.loc[df["age"].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### Cats younger than three

In [9]:
df.loc[(df["animal"] == "cat") & (df["age"] < 3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### Records with ages between two and four, inclusive

In [10]:
df.loc[df["age"].between(2, 4, inclusive="both")]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

## 6. Update the data

### Change the age in row `f` to 1.5

In [11]:
df.loc["f", "age"] = 1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

## 7. Aggregate and summarize

### Total number of visits

In [12]:
total_visits = df["visits"].sum()
total_visits

np.int64(19)

### Mean age by animal type

In [13]:
mean_age_by_animal = df.groupby("animal", dropna=False)["age"].mean()
mean_age_by_animal

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

## 8. Add and remove a row

In [14]:
df.loc["k"] = ["dog", 4.0, 2, "yes"]
df_with_new_row = df.copy()

df = df.drop(index="k")

print("DataFrame after adding row k:")
display(df_with_new_row)

print("DataFrame after removing row k:")
display(df)

DataFrame after adding row k:

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    dog  4.0       2      yes

DataFrame after removing row k:

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

## 9. Count and sort records

### Number of records for each animal type

In [15]:
df["animal"].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### Sort by age descending and visits ascending

In [16]:
df.sort_values(by=["age", "visits"], ascending=[False, True], na_position="last")

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

## 10. Create a pivot table

In [17]:
age_pivot = df.pivot_table(
    index="animal",
    columns="visits",
    values="age",
    aggfunc="mean",
)

age_pivot

visits    1    2     3
animal
cat     2.5  NaN  2.25
dog     3.0  6.0   NaN
snake   4.5  0.5   NaN

## Conclusion

This exercise demonstrates a complete introductory pandas workflow: constructing a DataFrame, inspecting its structure, selecting and filtering records, handling missing values, changing data, calculating summary statistics, and reshaping the results with a pivot table.